name: MCNSAModReq
version: 1.0
author: maboughey (maboughey@gmail.com)
main: uk.co.maboughey.mcnsamodreq.ModReq
depend: [MCNSANotes]
api-version: 1.13
commands:
    modreq:
        description: Send or view mod requests
        permission: modreq.player
        aliases: mr
    modreqmod:
        description: Mod Request commands for mods
        permission: modreq.mod
        aliases: mrm
    modreqadmin:
        description: View escalated mod requests
        permission: modreq.admin
        aliases: mra